//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graceterm {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graceterm.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request received, but this application instance is not accepting new requests because it asked for terminate (eg.: a sigterm were received). Responding as service unavailable (HTTP 503)..
        /// </summary>
        internal static string IrregularRequestReceived {
            get {
                return ResourceManager.GetString("IrregularRequestReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigterm received, waiting for pending requests to complete..
        /// </summary>
        internal static string SigtermReceived {
            get {
                return ResourceManager.GetString("SigtermReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending requests were completed, application will now terminate gracefully..
        /// </summary>
        internal static string TerminatingGracefully {
            get {
                return ResourceManager.GetString("TerminatingGracefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out! Application will terminate with {RequestCount} pedding requests..
        /// </summary>
        internal static string TimedOut {
            get {
                return ResourceManager.GetString("TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for pending requests, current request count: {RequestCount}.
        /// </summary>
        internal static string WaitingForPendingRequests {
            get {
                return ResourceManager.GetString("WaitingForPendingRequests", resourceCulture);
            }
        }
    }
}
